export const GET_NETFLIX_ORIGINALS = 'GET_NETFLIX_ORIGINALS';
export const GET_TRENDING_MOVIES = 'GET_TRENDING_MOVIES';
export const GET_TOPRATE_MOVIES = 'GET_TOPRATE_MOVIVES';
export const GET_ACTION_MOVIES = 'GET_ACTION_MOVIES';
export const GET_SEARCH_MOVIES = 'GET_SEARCH_MOVIES';

export const SET_MOVIE_DETAIL = 'SET_MOVIE_DETAIL';
